# Generated by Django 4.0.4 on 2022-08-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('postcode', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField()),
                ('temp', models.FloatField()),
                ('uv', models.FloatField()),
            ],
        ),
    ]
