# Generated by Django 4.0.4 on 2022-10-10 11:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1280)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1280)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteration3.category')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('blood_sugar_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insulin', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1280)),
                ('portion', models.CharField(max_length=1280)),
                ('description', models.CharField(max_length=1280)),
                ('portion_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
            },
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1280)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteration3.category')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteration3.description')),
            ],
        ),
        migrations.CreateModel(
            name='Diary_Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('category', models.CharField(max_length=1280)),
                ('description', models.CharField(max_length=1280)),
                ('portion', models.CharField(max_length=1280)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iteration3.diaryentries')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
