# Generated by Django 4.0.4 on 2022-10-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteration3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentries',
            name='comment',
            field=models.CharField(default=None, max_length=1280),
        ),
    ]
