# Generated by Django 4.0.4 on 2022-10-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iteration3', '0002_diaryentries_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary_menu',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='iteration3.user'),
        ),
        migrations.AddField(
            model_name='diaryentries',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='iteration3.user'),
        ),
    ]
