# Generated by Django 4.0.4 on 2022-10-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iteration3', '0003_diary_menu_user_diaryentries_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentries',
            name='comment',
            field=models.CharField(max_length=1280, null=True),
        ),
    ]
